name: Update Full

on: [push]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Update Packages
        run: |
          chmod +x ./updaterepo.sh
          ./updaterepo.sh
      - run:  |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit -a -m "Packages updated. <Auto Action>"
        git push
