name: Update_Packages
on: [push]
jobs:
  Update_Job-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: chmod +x ./updaterepo.sh
      - run: ./updaterepo.sh
#You can only edit email,username & message.
      - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "Turann's bot"
      - run: git add .
      - run: git commit -a -m "Packages updated. <Auto Action>"
      - run: git push
